//go:build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleControlPlane) DeepCopyInto(out *AnsibleControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleControlPlane.
func (in *AnsibleControlPlane) DeepCopy() *AnsibleControlPlane {
	if in == nil {
		return nil
	}
	out := new(AnsibleControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnsibleControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleControlPlaneList) DeepCopyInto(out *AnsibleControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnsibleControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleControlPlaneList.
func (in *AnsibleControlPlaneList) DeepCopy() *AnsibleControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(AnsibleControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnsibleControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleControlPlaneSpec) DeepCopyInto(out *AnsibleControlPlaneSpec) {
	*out = *in
	if in.EtcdReplicas != nil {
		in, out := &in.EtcdReplicas, &out.EtcdReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.MachineTemplate.DeepCopyInto(&out.MachineTemplate)
	in.AnsibleConfigSpec.DeepCopyInto(&out.AnsibleConfigSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleControlPlaneSpec.
func (in *AnsibleControlPlaneSpec) DeepCopy() *AnsibleControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(AnsibleControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleControlPlaneStatus) DeepCopyInto(out *AnsibleControlPlaneStatus) {
	*out = *in
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.ControlPlaneInitialMachine != nil {
		in, out := &in.ControlPlaneInitialMachine, &out.ControlPlaneInitialMachine
		*out = new(v1.ObjectReference)
		**out = **in
	}
	if in.EtcdInitialMachines != nil {
		in, out := &in.EtcdInitialMachines, &out.EtcdInitialMachines
		*out = make([]v1.ObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.FailureMessage != nil {
		in, out := &in.FailureMessage, &out.FailureMessage
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1beta1.Conditions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleControlPlaneStatus.
func (in *AnsibleControlPlaneStatus) DeepCopy() *AnsibleControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(AnsibleControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleControlPlaneTemplate) DeepCopyInto(out *AnsibleControlPlaneTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleControlPlaneTemplate.
func (in *AnsibleControlPlaneTemplate) DeepCopy() *AnsibleControlPlaneTemplate {
	if in == nil {
		return nil
	}
	out := new(AnsibleControlPlaneTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnsibleControlPlaneTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleControlPlaneTemplateList) DeepCopyInto(out *AnsibleControlPlaneTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AnsibleControlPlaneTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleControlPlaneTemplateList.
func (in *AnsibleControlPlaneTemplateList) DeepCopy() *AnsibleControlPlaneTemplateList {
	if in == nil {
		return nil
	}
	out := new(AnsibleControlPlaneTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnsibleControlPlaneTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleControlPlaneTemplateResource) DeepCopyInto(out *AnsibleControlPlaneTemplateResource) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleControlPlaneTemplateResource.
func (in *AnsibleControlPlaneTemplateResource) DeepCopy() *AnsibleControlPlaneTemplateResource {
	if in == nil {
		return nil
	}
	out := new(AnsibleControlPlaneTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnsibleControlPlaneTemplateSpec) DeepCopyInto(out *AnsibleControlPlaneTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnsibleControlPlaneTemplateSpec.
func (in *AnsibleControlPlaneTemplateSpec) DeepCopy() *AnsibleControlPlaneTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(AnsibleControlPlaneTemplateSpec)
	in.DeepCopyInto(out)
	return out
}
